eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
     waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
