eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  server:
     waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
